name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
permissions:
  contents: read

jobs:
  coverage:
    name: Test with coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: npm
      - run: npm cli
      - run: npm run test:coverage
      - uses: actions/upload-artifact@v7
        with:
          name: test-coverage-report
          path: coverage/
